[package]
name = "egui-macroquad"
version = "0.1.0"
authors = ["ilya sheprut <optozorax@gmail.com>"]
edition = "2018"

[dependencies]
emigui-miniquad = { git = "https://github.com/not-fl3/egui-miniquad" }
macroquad = "0.3.0-alpha.16"
egui = "0.10.0"

[dev-dependencies]
egui_demo_lib = "0.10.0"
