[package]
name = "egui-macroquad"
version = "0.1.0"
authors = ["ilya sheprut <optozorax@gmail.com>"]
edition = "2018"

[dependencies]
egui = "0.10.0"
# merge `add-draw-call` and `fix-url-wasm` into `https://github.com/optozorax/egui-miniquad/` and use here.
# egui-miniquad = { git = "https://github.com/optozorax/egui-miniquad/", branch = "add-draw-call" }
egui-miniquad = { path = "../egui-miniquad" }
macroquad = { git = "https://github.com/not-fl3/macroquad", commit = "1257a2b" }

[dev-dependencies]
egui_demo_lib = "0.10.0"
